# Generated by Django 3.0.8 on 2020-07-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AccAggApp', '0002_profile_pan'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accnum',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='accrefnum',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
