# Generated by Django 3.0.8 on 2020-07-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccAggApp', '0003_auto_20200716_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='accnum',
            new_name='accountNo',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='accrefnum',
            new_name='accountRefNo',
        ),
    ]
