# Generated by Django 3.0.8 on 2020-07-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AccAggApp', '0004_auto_20200716_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
