# Generated by Django 3.0.8 on 2020-07-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AccAggApp', '0006_profile_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banklink',
            field=models.BooleanField(default=False),
        ),
    ]
