# Generated by Django 3.0.8 on 2020-07-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccAggApp', '0008_profile_txnid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='userID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
