# Generated by Django 3.0.8 on 2020-07-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccAggApp', '0013_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rid',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
