# Generated by Django 3.0.8 on 2020-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AccAggApp', '0014_profile_rid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ftoken',
            field=models.TextField(blank=True),
        ),
    ]
